spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations:
      - classpath:db/migration

  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}