spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/baegopang
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-seed

  jpa:
    show-sql: true

toss:
  payments:
    secret-key: test_sk_dummy
    base-url: https://api.tosspayments.com
jwt:
  secret: my-super-secret-key-my-super-secret-key
  access-token-expiration-seconds: 3600000
  refresh-token-expiration-seconds: 1209600000

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.context.config: DEBUG

file:
  upload-dir: uploads

# TODO: 추후 S3 전환 시 추가 예정
# cloud:
#   aws:
#     credentials:
#       access-key: ${AWS_ACCESS_KEY}
#       secret-key: ${AWS_SECRET_KEY}
#     region:
#       static: ap-northeast-2
#     s3:
#       bucket: ${AWS_S3_BUCKET}