spring:
  config:
    activate:
      on-profile: local   # ✅ local 프로필에서만 이 파일 적용

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-seed

  logging:
    level:
      org.flywaydb: DEBUG
      org.springframework.boot.context.config: DEBUG